name: Release on Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip repository
        run: zip -r repo.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: repo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

