name: Release on Push

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip repo contents
        run: |
          zip -r repo.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.sha }}
          name: "Release ${{ github.sha }}"
          files: repo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
